import { EnrichmentConfig } from '../types/enrichment.types';

export const ENRICHMENT_CONFIG: EnrichmentConfig = {
  organizationAliases: [
    {
      standardName: 'Google',
      aliases: ['Google LLC', 'Google Inc', 'Google Inc.', 'Google Careers', 'Google India'],
    },
    {
      standardName: 'Microsoft',
      aliases: ['Microsoft Corporation', 'MSFT', 'Microsoft India', 'Microsoft Inc.'],
    },
    {
      standardName: 'Indian Institute of Technology Delhi',
      aliases: ['IIT Delhi', 'IITD', 'Indian Institute of Technology, Delhi'],
    },
    {
      standardName: 'Indian Institute of Technology Bombay',
      aliases: ['IIT Bombay', 'IITB', 'Indian Institute of Technology, Bombay'],
    },
    {
      standardName: 'Government of India',
      aliases: ['Govt. of India', 'Govt of India', 'GOI', 'Government of India (GOI)'],
    },
    {
      standardName: 'Amazon',
      aliases: ['Amazon Web Services', 'AWS', 'Amazon.com', 'Amazon India', 'Amazon Dev Centre'],
    },
    {
      standardName: 'Meta',
      aliases: ['Meta Platforms Inc.', 'Facebook', 'Facebook Inc.', 'Meta Careers'],
    },
    {
      standardName: 'Apple',
      aliases: ['Apple Inc.', 'Apple Careers', 'Apple India'],
    },
  ],

  domainSourceMappings: [
    {
      suffixes: ['.gov', '.gov.in', '.nic.in', '.gov.uk', '.gov.us', 'gov.'],
      sourceType: 'GOVERNMENT',
    },
    {
      suffixes: ['.edu', '.edu.in', '.ac.in', '.ac.uk', '.edu.co', 'ac.nz', 'college.edu'],
      sourceType: 'UNIVERSITY',
    },
    {
      suffixes: [
        'internshala.com',
        'linkedin.com',
        'indeed.com',
        'naukri.com',
        'glassdoor.com',
        'unstop.com',
        'ycombinator.com/jobs',
      ],
      sourceType: 'AGGREGATOR',
    },
    {
      suffixes: ['github.com', 'devpost.com', 'discord.gg', 'meetup.com'],
      sourceType: 'COMMUNITY',
    },
    {
      suffixes: ['.org', '.ngo.in', 'unesco.org', 'unicef.org', 'who.int'],
      sourceType: 'NGO',
    },
  ],

  categoryKeywords: [
    {
      category: 'Artificial Intelligence & Machine Learning',
      keywords: [
        'ai',
        'artificial intelligence',
        'machine learning',
        'ml',
        'deep learning',
        'neural networks',
        'nlp',
        'computer vision',
        'data science',
        'llm',
        'generative ai',
        'genai',
      ],
    },
    {
      category: 'Backend Development',
      keywords: [
        'backend',
        'back-end',
        'node',
        'nodejs',
        'express',
        'nest',
        'nestjs',
        'python',
        'django',
        'flask',
        'fastapi',
        'java',
        'spring',
        'springboot',
        'go',
        'golang',
        'rust',
        'ruby',
        'rails',
        'sql',
        'postgresql',
        'mongodb',
        'redis',
        'database',
        'api',
        'graphql',
      ],
    },
    {
      category: 'Frontend Development',
      keywords: [
        'frontend',
        'front-end',
        'react',
        'reactjs',
        'vue',
        'vuejs',
        'angular',
        'svelte',
        'nextjs',
        'next.js',
        'html',
        'css',
        'sass',
        'tailwind',
        'javascript',
        'typescript',
        'webpack',
        'vite',
      ],
    },
    {
      category: 'Software Development',
      keywords: [
        'software development',
        'software engineer',
        'software engineering',
        'swe',
        'sde',
        'developer',
        'application developer',
        'full stack',
        'fullstack',
        'programming',
        'programmer',
        'coding',
      ],
    },
    {
      category: 'Cyber Security',
      keywords: [
        'cyber security',
        'cybersecurity',
        'information security',
        'infosec',
        'penetration testing',
        'pentesting',
        'ethical hacking',
        'cryptography',
        'security analyst',
        'soc',
        'malware',
      ],
    },
    {
      category: 'Electronics & Hardware',
      keywords: [
        'electronics',
        'hardware',
        'embedded',
        'iot',
        'robotics',
        'vlsi',
        'microcontroller',
        'arduino',
        'raspberry pi',
        'electrical',
        'circuit',
        'fpga',
      ],
    },
    {
      category: 'Research',
      keywords: [
        'research',
        'researcher',
        'scientific',
        'academic',
        'fellow',
        'phd',
        'postdoc',
        'lab',
        'laboratory',
        'paper publication',
        'symposium',
      ],
    },
    {
      category: 'Healthcare & Biotech',
      keywords: [
        'healthcare',
        'health',
        'biotech',
        'biotechnology',
        'medical',
        'medicine',
        'pharmaceutical',
        'pharma',
        'clinical',
        'biological',
        'bioinformatics',
      ],
    },
    {
      category: 'Finance & Fintech',
      keywords: [
        'finance',
        'fintech',
        'financial',
        'banking',
        'investment',
        'trading',
        'quantitative',
        'quant',
        'accounting',
        'auditing',
        'crypto',
        'blockchain',
      ],
    },
    {
      category: 'Marketing & Sales',
      keywords: [
        'marketing',
        'sales',
        'growth',
        'seo',
        'social media',
        'content marketing',
        'branding',
        'advertising',
        'copywriting',
        'pr',
        'public relations',
      ],
    },
    {
      category: 'Design & Creative',
      keywords: [
        'design',
        'designer',
        'ui/ux',
        'ux/ui',
        'user interface',
        'user experience',
        'figma',
        'graphic design',
        'illustrator',
        'photoshop',
        'animation',
        'creative',
        'video editing',
      ],
    },
    {
      category: 'Content & Journalism',
      keywords: [
        'content writer',
        'writing',
        'editor',
        'journalism',
        'blogging',
        'technical writer',
        'copywriter',
      ],
    },
    {
      category: 'Business & Management',
      keywords: [
        'business analyst',
        'product manager',
        'product management',
        'pm',
        'operations',
        'project manager',
        'project management',
        'consulting',
        'hr',
        'human resources',
        'recruiter',
      ],
    },
    {
      category: 'Education',
      keywords: [
        'education',
        'teaching',
        'teacher',
        'tutor',
        'curriculum',
        'instructional design',
        'e-learning',
        'academic mentor',
      ],
    },
    {
      category: 'Government & Public Policy',
      keywords: [
        'government',
        'ministry',
        'public policy',
        'civil services',
        'policy research',
        'diplomacy',
        'un',
        'united nations',
      ],
    },
    {
      category: 'Entrepreneurship',
      keywords: [
        'startup',
        'founder',
        'co-founder',
        'entrepreneur',
        'entrepreneurship',
        'incubator',
        'accelerator',
        'venture capital',
        'vc',
      ],
    },
    {
      category: 'Women Empowerment',
      keywords: [
        'women',
        'female',
        'girl',
        'girls',
        'diversity',
        'women in tech',
        'women in stem',
        'womxn',
        'shecodes',
        'wekeynote',
      ],
    },
  ],

  metadataKeywords: {
    government: [
      'govt',
      'government',
      'ministry',
      'department of',
      'national institute',
      'official website of',
      'public sector',
      'municipal',
      'embassy',
      'bureau',
      'parliament',
      'council of',
    ],
    remote: [
      'remote',
      'work from home',
      'wfh',
      'work-from-home',
      'anywhere',
      'virtual internship',
      'remote-first',
      'flexible location',
      'home-based',
    ],
    paidStipend: [
      'paid',
      'stipend',
      'salary',
      'compensation',
      'per month',
      'pm',
      'hourly rate',
      'reimbursement',
      'allowance',
      'remuneration',
      'pay scale',
      'lpa',
      'ctc',
      'usd',
      'eur',
      'inr',
    ],
    resume: ['resume', 'cv', 'curriculum vitae', 'bio-data', 'biodata', 'profile'],
    portfolio: [
      'portfolio',
      'github link',
      'behance',
      'dribbble',
      'sample work',
      'work samples',
      'personal website',
      'project links',
      'writing sample',
    ],
    experience: [
      'experience',
      'years of experience',
      'yoe',
      'years experience',
      'experienced in',
      'prior work',
      'previous experience',
      'minimum 1 year',
      'minimum 2 years',
      'minimum 3 years',
      'undergraduates with experience',
    ],
    degree: [
      'degree',
      'bachelor',
      'bachelors',
      'master',
      'masters',
      'phd',
      'graduate',
      'graduation',
      'undergraduate',
      'diploma',
      'b.tech',
      'm.tech',
      'bca',
      'mca',
      'bs',
      'ms',
      'b.sc',
      'm.sc',
      'mba',
    ],
    countries: {
      India: [
        'india',
        'indian',
        'delhi',
        'mumbai',
        'bangalore',
        'bengaluru',
        'pune',
        'hyderabad',
        'chennai',
        'kolkata',
        'noida',
        'gurgaon',
        '.in',
      ],
      'United States': [
        'united states',
        'usa',
        'u.s.a',
        'u.s.',
        'american',
        'california',
        'new york',
        'texas',
        'san francisco',
        'seattle',
        '.us',
      ],
      'United Kingdom': [
        'united kingdom',
        'uk',
        'u.k.',
        'london',
        'british',
        'england',
        'scotland',
        '.uk',
      ],
      Canada: ['canada', 'canadian', 'toronto', 'vancouver', 'montreal', '.ca'],
      Germany: ['germany', 'german', 'berlin', 'munich', '.de'],
      Singapore: ['singapore', 'singaporean', '.sg'],
      Australia: ['australia', 'australian', 'sydney', 'melbourne', '.au'],
    },
  },
};
