export interface Ecosystem {
  id: string;
  displayName: string;
  domains: string[];
  searchTemplates: string[];
  crawlStrategy: 'direct' | 'search' | 'sitemap' | 'rss';
  parserType: string;
  trustScore: number;
  priority: 'critical' | 'high' | 'medium' | 'low';
}

export const ECOSYSTEMS: Record<string, Ecosystem> = {
  Ashby: {
    id: 'Ashby',
    displayName: 'Ashby',
    domains: ['jobs.ashbyhq.com'],
    searchTemplates: [
      'site:jobs.ashbyhq.com {keyword} {location}',
      'site:jobs.ashbyhq.com {keyword} remote',
      'site:jobs.ashbyhq.com internship',
      'site:jobs.ashbyhq.com engineering intern',
    ],
    crawlStrategy: 'direct',
    parserType: 'ashby',
    trustScore: 98,
    priority: 'critical',
  },
  Greenhouse: {
    id: 'Greenhouse',
    displayName: 'Greenhouse',
    domains: ['boards.greenhouse.io'],
    searchTemplates: [
      'site:boards.greenhouse.io {keyword} {location}',
      'site:boards.greenhouse.io {keyword} remote',
      'site:boards.greenhouse.io internship',
      'site:boards.greenhouse.io software intern',
    ],
    crawlStrategy: 'direct',
    parserType: 'greenhouse',
    trustScore: 98,
    priority: 'critical',
  },
  Lever: {
    id: 'Lever',
    displayName: 'Lever',
    domains: ['jobs.lever.co'],
    searchTemplates: [
      'site:jobs.lever.co {keyword} {location}',
      'site:jobs.lever.co {keyword} remote',
      'site:jobs.lever.co internship',
      'site:jobs.lever.co engineering intern',
    ],
    crawlStrategy: 'direct',
    parserType: 'lever',
    trustScore: 98,
    priority: 'critical',
  },
  Wellfound: {
    id: 'Wellfound',
    displayName: 'Wellfound',
    domains: ['wellfound.com', 'angel.co'],
    searchTemplates: [
      'site:wellfound.com {keyword} {location}',
      'site:wellfound.com {keyword} remote',
      'site:wellfound.com internship',
    ],
    crawlStrategy: 'search',
    parserType: 'wellfound',
    trustScore: 90,
    priority: 'high',
  },
  Workable: {
    id: 'Workable',
    displayName: 'Workable',
    domains: ['apply.workable.com', 'jobs.workable.com'],
    searchTemplates: [
      'site:apply.workable.com {keyword} {location}',
      'site:apply.workable.com {keyword} remote',
    ],
    crawlStrategy: 'direct',
    parserType: 'workable',
    trustScore: 90,
    priority: 'medium',
  },
  SmartRecruiters: {
    id: 'SmartRecruiters',
    displayName: 'SmartRecruiters',
    domains: ['jobs.smartrecruiters.com'],
    searchTemplates: [
      'site:jobs.smartrecruiters.com {keyword} {location}',
      'site:jobs.smartrecruiters.com {keyword} remote',
    ],
    crawlStrategy: 'direct',
    parserType: 'smartrecruiters',
    trustScore: 90,
    priority: 'medium',
  },
  Jobvite: {
    id: 'Jobvite',
    displayName: 'Jobvite',
    domains: ['jobs.jobvite.com'],
    searchTemplates: ['site:jobs.jobvite.com {keyword} {location}'],
    crawlStrategy: 'direct',
    parserType: 'jobvite',
    trustScore: 88,
    priority: 'medium',
  },
  Devfolio: {
    id: 'Devfolio',
    displayName: 'Devfolio',
    domains: ['devfolio.co'],
    searchTemplates: ['site:devfolio.co hackathon', 'site:devfolio.co/hackathons'],
    crawlStrategy: 'search',
    parserType: 'devfolio',
    trustScore: 92,
    priority: 'high',
  },
  Devpost: {
    id: 'Devpost',
    displayName: 'Devpost',
    domains: ['devpost.com'],
    searchTemplates: ['site:devpost.com hackathon'],
    crawlStrategy: 'search',
    parserType: 'devpost',
    trustScore: 92,
    priority: 'high',
  },
  Unstop: {
    id: 'Unstop',
    displayName: 'Unstop',
    domains: ['unstop.com'],
    searchTemplates: ['site:unstop.com internship', 'site:unstop.com competition'],
    crawlStrategy: 'search',
    parserType: 'unstop',
    trustScore: 85,
    priority: 'medium',
  },
  GitHubPrograms: {
    id: 'GitHubPrograms',
    displayName: 'GitHub Programs',
    domains: ['github.com/education', 'github.com'],
    searchTemplates: ['site:github.com "internship" OR "externship"'],
    crawlStrategy: 'search',
    parserType: 'github-programs',
    trustScore: 95,
    priority: 'high',
  },
  GooglePrograms: {
    id: 'GooglePrograms',
    displayName: 'Google Programs',
    domains: ['buildyourcareerwithgoogle.com', 'careers.google.com'],
    searchTemplates: ['site:careers.google.com/jobs {keyword}'],
    crawlStrategy: 'direct',
    parserType: 'google',
    trustScore: 99,
    priority: 'critical',
  },
  MicrosoftCareers: {
    id: 'MicrosoftCareers',
    displayName: 'Microsoft Careers',
    domains: ['careers.microsoft.com'],
    searchTemplates: ['site:careers.microsoft.com {keyword}'],
    crawlStrategy: 'direct',
    parserType: 'microsoft',
    trustScore: 99,
    priority: 'critical',
  },
  MetaCareers: {
    id: 'MetaCareers',
    displayName: 'Meta Careers',
    domains: ['metacareers.com'],
    searchTemplates: ['site:metacareers.com {keyword}'],
    crawlStrategy: 'direct',
    parserType: 'meta',
    trustScore: 99,
    priority: 'critical',
  },
  AmazonJobs: {
    id: 'AmazonJobs',
    displayName: 'Amazon Jobs',
    domains: ['amazon.jobs'],
    searchTemplates: ['site:amazon.jobs {keyword}'],
    crawlStrategy: 'direct',
    parserType: 'amazon',
    trustScore: 99,
    priority: 'critical',
  },
  LinkedInJobs: {
    id: 'LinkedInJobs',
    displayName: 'LinkedIn Jobs',
    domains: ['linkedin.com/jobs'],
    searchTemplates: ['site:linkedin.com/jobs {keyword} {location}'],
    crawlStrategy: 'search',
    parserType: 'linkedin',
    trustScore: 75,
    priority: 'low',
  },
  YCJobs: {
    id: 'YCJobs',
    displayName: 'YC Jobs',
    domains: ['workatastartup.com'],
    searchTemplates: ['site:workatastartup.com {keyword}'],
    crawlStrategy: 'search',
    parserType: 'yc',
    trustScore: 95,
    priority: 'high',
  },
};
export default ECOSYSTEMS;
