export const DISCOVERY_CONFIG = {
  MAX_SEARCH_QUERIES: 25,
  MAX_TAVILY_RESULTS_PER_QUERY: 3,
  MAX_PAGES_RETURNED_OVERALL: 60,
  CONCURRENCY_LIMIT: 5,
  CACHE_TTL_SECONDS: 21600, // 6 hours
  HEURISTICS: {
    TRUST: {
      HIGH: 10,
      MEDIUM: 5,
      LOW: 0,
    },
    KEYWORD_BOOST: 4,
    FRESHNESS_BOOST: 2,
    URL_QUALITY_BOOST: 1,
  },
};
