export const DISCOVERY_CONFIG = {
  MAX_SEARCH_QUERIES: 25,
  MAX_TAVILY_RESULTS_PER_QUERY: 3,
  MAX_PAGES_RETURNED_OVERALL: 60,
  CONCURRENCY_LIMIT: 5,
  CACHE_TTL_SECONDS: 21600, // 6 hours

  // Firecrawl Extraction Constraints
  MAX_EXTRACTIONS: 15,
  FIRECRAWL_TIMEOUT: 30000, // 30s
  FIRECRAWL_RETRIES: 2,
  FIRECRAWL_CACHE_TTL_SECONDS: 86400, // 24 hours
  CONCURRENCY_EXTRACTION: 3,
  SKIP_EXTRACTION_THRESHOLD: {
    SNIPPET_LENGTH: 150,
    SCORE: 12,
  },

  HEURISTICS: {
    TRUST: {
      HIGH: 10,
      MEDIUM: 5,
      LOW: 0,
    },
    KEYWORD_BOOST: 4,
    FRESHNESS_BOOST: 2,
    URL_QUALITY_BOOST: 1,
  },

  QUALITY: {
    ACCEPT_THRESHOLD: 75,
    REVIEW_THRESHOLD: 60,
  },
};
