import { CityIntel, Ecosystem } from './ecosystem.types';

/**
 * Deterministic ecosystem + city registry.
 *
 * No network, no LLM. Every ecosystem and city is curated statically so the
 * engine scales without architectural change. Strategies read from this
 * registry; networks are never required for deterministic discovery.
 */

const UPDATED = Date.UTC(2026, 6, 18);

/**
 * Curated ecosystems. Adding a new ecosystem is a pure configuration change
 * (no business logic edits required).
 */
export const ECOSYSTEMS: Ecosystem[] = [
  // ─── Accelerators ───────────────────────────────────────────────────────
  {
    id: 'yc',
    name: 'Y Combinator',
    type: 'ACCELERATOR',
    country: 'USA',
    region: 'GLOBAL',
    priority: 1,
    officialWebsite: 'https://www.ycombinator.com',
    portfolioPage: 'https://www.ycombinator.com/companies',
    companiesPage: 'https://www.ycombinator.com/companies',
    rssFeed: 'https://www.ycombinator.com/blog/rss.xml',
    knownCareerPages: ['https://www.ycombinator.com/companies'],
    knownATS: [],
    knownDomains: [
      'openai.com',
      'stripe.com',
      'airbnb.com',
      'doordash.com',
      'instacart.com',
      'cursor.com',
      'retool.com',
      'ramp.com',
      'coinbase.com',
    ],
    knownPartners: ['techstars', 'antler', '500global'],
    knownUniversities: [],
    knownAccelerators: ['techstars', 'antler'],
    knownIncubators: [],
    knownEvents: ['YC Startup School', 'YC Demo Day'],
    engineeringFocus: ['AI', 'SAAS', 'FINTECH', 'DEVELOPER_TOOLS'],
    internshipLikelihood: 0.92,
    remoteFriendliness: 0.8,
    lastUpdated: UPDATED,
  },
  {
    id: 'techstars',
    name: 'Techstars',
    type: 'ACCELERATOR',
    country: 'USA',
    region: 'GLOBAL',
    priority: 1,
    officialWebsite: 'https://www.techstars.com',
    portfolioPage: 'https://www.techstars.com/companies',
    knownCareerPages: ['https://www.techstars.com/companies'],
    knownATS: [],
    knownDomains: ['sendgrid.com', 'zayo.com', 'classpass.com', 'digitalocean.com'],
    knownPartners: ['yc', 'antler'],
    knownUniversities: [],
    knownAccelerators: ['yc', 'antler'],
    knownIncubators: [],
    knownEvents: ['Techstars Demo Day'],
    engineeringFocus: ['SAAS', 'CLOUD', 'DEVELOPER_TOOLS'],
    internshipLikelihood: 0.78,
    remoteFriendliness: 0.7,
    lastUpdated: UPDATED,
  },
  {
    id: 'antler',
    name: 'Antler',
    type: 'ACCELERATOR',
    country: 'Singapore',
    region: 'APAC',
    priority: 2,
    officialWebsite: 'https://www.antler.co',
    portfolioPage: 'https://www.antler.co/companies',
    knownCareerPages: ['https://www.antler.co/careers'],
    knownATS: [],
    knownDomains: ['tensorflight.com', 'hevodata.com', 'epifi.com', 'covr.com'],
    knownPartners: ['yc', 'techstars'],
    knownUniversities: [],
    knownAccelerators: ['yc', 'techstars'],
    knownIncubators: [],
    knownEvents: ['Antler Residency'],
    engineeringFocus: ['AI', 'FINTECH', 'DEEPTECH'],
    internshipLikelihood: 0.7,
    remoteFriendliness: 0.65,
    lastUpdated: UPDATED,
  },
  {
    id: '500global',
    name: '500 Global',
    type: 'ACCELERATOR',
    country: 'USA',
    region: 'GLOBAL',
    priority: 2,
    officialWebsite: 'https://500.co',
    portfolioPage: 'https://500.co/portfolio',
    knownCareerPages: ['https://500.co/careers'],
    knownATS: [],
    knownDomains: ['canva.com', 'talkdesk.com', 'grab.com'],
    knownPartners: ['yc'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: [],
    knownEvents: ['500 Demo Day'],
    engineeringFocus: ['SAAS', 'FINTECH', 'AI'],
    internshipLikelihood: 0.66,
    remoteFriendliness: 0.6,
    lastUpdated: UPDATED,
  },
  {
    id: 'ef',
    name: 'Entrepreneur First',
    type: 'ACCELERATOR',
    country: 'UK',
    region: 'EUROPE',
    priority: 2,
    officialWebsite: 'https://www.joinef.com',
    portfolioPage: 'https://www.joinef.com/companies',
    knownCareerPages: ['https://www.joinef.com/careers'],
    knownATS: [],
    knownDomains: [],
    knownPartners: ['yc', 'antler'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: [],
    knownEvents: ['EF Cohort'],
    engineeringFocus: ['AI', 'DEEPTECH'],
    internshipLikelihood: 0.62,
    remoteFriendliness: 0.7,
    lastUpdated: UPDATED,
  },
  {
    id: 'foundersfactory',
    name: 'Founders Factory',
    type: 'ACCELERATOR',
    country: 'UK',
    region: 'EUROPE',
    priority: 3,
    officialWebsite: 'https://foundersfactory.com',
    portfolioPage: 'https://foundersfactory.com/portfolio',
    knownCareerPages: ['https://foundersfactory.com/careers'],
    knownATS: [],
    knownDomains: [],
    knownPartners: ['ef'],
    knownUniversities: [],
    knownAccelerators: ['ef'],
    knownIncubators: [],
    knownEvents: ['Founders Factory Cohort'],
    engineeringFocus: ['AI', 'SAAS'],
    internshipLikelihood: 0.55,
    remoteFriendliness: 0.5,
    lastUpdated: UPDATED,
  },
  {
    id: 'sosv',
    name: 'SOSV',
    type: 'ACCELERATOR',
    country: 'USA',
    region: 'GLOBAL',
    priority: 2,
    officialWebsite: 'https://sosv.com',
    portfolioPage: 'https://sosv.com/portfolio',
    knownCareerPages: ['https://sosv.com/careers'],
    knownATS: [],
    knownDomains: [],
    knownPartners: ['yc'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: ['thub'],
    knownEvents: ['SOSV Demo Day'],
    engineeringFocus: ['DEEPTECH', 'AI', 'CLOUD'],
    internshipLikelihood: 0.6,
    remoteFriendliness: 0.5,
    lastUpdated: UPDATED,
  },
  {
    id: 'plugandplay',
    name: 'Plug and Play',
    type: 'ACCELERATOR',
    country: 'USA',
    region: 'GLOBAL',
    priority: 2,
    officialWebsite: 'https://www.plugandplaytechcenter.com',
    portfolioPage: 'https://www.plugandplaytechcenter.com/startups',
    knownCareerPages: ['https://www.plugandplaytechcenter.com/careers'],
    knownATS: [],
    knownDomains: [],
    knownPartners: ['yc', '500global'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: ['thub'],
    knownEvents: ['Plug and Play Summit'],
    engineeringFocus: ['SAAS', 'FINTECH', 'AI'],
    internshipLikelihood: 0.58,
    remoteFriendliness: 0.55,
    lastUpdated: UPDATED,
  },

  // ─── VC-backed ecosystems ───────────────────────────────────────────────
  {
    id: 'peakxv',
    name: 'Peak XV',
    type: 'VC_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 1,
    officialWebsite: 'https://www.peakxv.com',
    portfolioPage: 'https://www.peakxv.com/companies',
    knownCareerPages: ['https://www.peakxv.com/careers'],
    knownATS: [],
    knownDomains: ['groww.in', 'dream11.com', 'gupshup.io', 'licious.in', 'mcaffeine.com'],
    knownPartners: ['accel', 'blume'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: ['thub', 'nsrcel'],
    knownEvents: ['Peak XV Surge'],
    engineeringFocus: ['FINTECH', 'SAAS', 'AI'],
    internshipLikelihood: 0.85,
    remoteFriendliness: 0.6,
    lastUpdated: UPDATED,
  },
  {
    id: 'accel',
    name: 'Accel',
    type: 'VC_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 1,
    officialWebsite: 'https://www.accel.com',
    portfolioPage: 'https://www.accel.com/portfolio',
    knownCareerPages: ['https://www.accel.com/careers'],
    knownATS: [],
    knownDomains: [
      'flipkart.com',
      'swiggy.com',
      'zomato.com',
      'freshworks.com',
      'browserstack.com',
    ],
    knownPartners: ['peakxv', 'blume'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: ['thub'],
    knownEvents: ['Accel Sprint'],
    engineeringFocus: ['SAAS', 'FINTECH', 'DEVELOPER_TOOLS'],
    internshipLikelihood: 0.84,
    remoteFriendliness: 0.6,
    lastUpdated: UPDATED,
  },
  {
    id: 'lightspeed',
    name: 'Lightspeed',
    type: 'VC_ECOSYSTEM',
    country: 'USA',
    region: 'GLOBAL',
    priority: 1,
    officialWebsite: 'https://lsvp.com',
    portfolioPage: 'https://lsvp.com/portfolio',
    knownCareerPages: ['https://lsvp.com/careers'],
    knownATS: [],
    knownDomains: ['cred.club', 'oyo.com', 'udemy.com'],
    knownPartners: ['accel', 'peakxv'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: ['thub'],
    knownEvents: ['Lightspeed Velocity'],
    engineeringFocus: ['SAAS', 'FINTECH', 'AI'],
    internshipLikelihood: 0.8,
    remoteFriendliness: 0.6,
    lastUpdated: UPDATED,
  },
  {
    id: 'blume',
    name: 'Blume Ventures',
    type: 'VC_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 2,
    officialWebsite: 'https://blume.vc',
    portfolioPage: 'https://blume.vc/portfolio',
    knownCareerPages: ['https://blume.vc/careers'],
    knownATS: [],
    knownDomains: ['porter.in', 'ofbusiness.com', 'unacademy.com', 'cashfree.com'],
    knownPartners: ['peakxv', 'accel'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: ['thub'],
    knownEvents: ['Blume Founder Office Hours'],
    engineeringFocus: ['SAAS', 'FINTECH'],
    internshipLikelihood: 0.74,
    remoteFriendliness: 0.55,
    lastUpdated: UPDATED,
  },
  {
    id: 'matrix',
    name: 'Matrix Partners',
    type: 'VC_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 2,
    officialWebsite: 'https://matrixpartners.in',
    portfolioPage: 'https://matrixpartners.in/portfolio',
    knownCareerPages: ['https://matrixpartners.in/careers'],
    knownATS: [],
    knownDomains: ['ofbusiness.com', 'dailyhunt.com'],
    knownPartners: ['accel', 'blume'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: ['thub'],
    knownEvents: ['Matrix Meet'],
    engineeringFocus: ['SAAS', 'FINTECH'],
    internshipLikelihood: 0.7,
    remoteFriendliness: 0.5,
    lastUpdated: UPDATED,
  },
  {
    id: 'kalaari',
    name: 'Kalaari Capital',
    type: 'VC_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 2,
    officialWebsite: 'https://kalaari.com',
    portfolioPage: 'https://kalaari.com/portfolio',
    knownCareerPages: ['https://kalaari.com/careers'],
    knownATS: [],
    knownDomains: ['cashfree.com', 'vectoredge.com'],
    knownPartners: ['blume', 'matrix'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: ['thub'],
    knownEvents: ['Kalaari CXXO'],
    engineeringFocus: ['SAAS', 'FINTECH'],
    internshipLikelihood: 0.68,
    remoteFriendliness: 0.5,
    lastUpdated: UPDATED,
  },
  {
    id: 'nexus',
    name: 'Nexus Venture Partners',
    type: 'VC_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 2,
    officialWebsite: 'https://nexusvp.com',
    portfolioPage: 'https://nexusvp.com/portfolio',
    knownCareerPages: ['https://nexusvp.com/careers'],
    knownATS: [],
    knownDomains: ['postman.com', 'delhivery.com', 'turtlefin.com'],
    knownPartners: ['accel', 'blume'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: ['thub'],
    knownEvents: ['Nexus Select'],
    engineeringFocus: ['SAAS', 'DEVELOPER_TOOLS'],
    internshipLikelihood: 0.72,
    remoteFriendliness: 0.6,
    lastUpdated: UPDATED,
  },
  {
    id: 'elevation',
    name: 'Elevation Capital',
    type: 'VC_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 2,
    officialWebsite: 'https://elevationcapital.com',
    portfolioPage: 'https://elevationcapital.com/portfolio',
    knownCareerPages: ['https://elevationcapital.com/careers'],
    knownATS: [],
    knownDomains: ['meesho.com', 'unacademy.com'],
    knownPartners: ['accel', 'blume'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: ['thub'],
    knownEvents: ['Elevation Bytes'],
    engineeringFocus: ['SAAS', 'FINTECH'],
    internshipLikelihood: 0.7,
    remoteFriendliness: 0.55,
    lastUpdated: UPDATED,
  },
  {
    id: '100xvc',
    name: '100X.VC',
    type: 'VC_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 3,
    officialWebsite: 'https://www.100x.vc',
    portfolioPage: 'https://www.100x.vc/portfolio',
    knownCareerPages: ['https://www.100x.vc/careers'],
    knownATS: [],
    knownDomains: [],
    knownPartners: ['blume', 'matrix'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: ['thub'],
    knownEvents: ['100X Class'],
    engineeringFocus: ['SAAS', 'AI'],
    internshipLikelihood: 0.6,
    remoteFriendliness: 0.5,
    lastUpdated: UPDATED,
  },
  {
    id: 'chiratae',
    name: 'Chiratae Ventures',
    type: 'VC_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 3,
    officialWebsite: 'https://chiratae.com',
    portfolioPage: 'https://chiratae.com/portfolio',
    knownCareerPages: ['https://chiratae.com/careers'],
    knownATS: [],
    knownDomains: ['bounce.com', 'healthifyme.com'],
    knownPartners: ['blume', 'kalaari'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: ['thub'],
    knownEvents: ['Chiratae Bytes'],
    engineeringFocus: ['SAAS', 'FINTECH'],
    internshipLikelihood: 0.58,
    remoteFriendliness: 0.5,
    lastUpdated: UPDATED,
  },

  // ─── Indian startup ecosystems ──────────────────────────────────────────
  {
    id: 'thub',
    name: 'T-Hub',
    type: 'INDIAN_STARTUP_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 1,
    officialWebsite: 'https://www.t-hub.co',
    portfolioPage: 'https://www.t-hub.co/startups',
    startupDirectory: 'https://www.t-hub.co/startups',
    knownCareerPages: ['https://www.t-hub.co/careers'],
    knownATS: [],
    knownDomains: [],
    knownPartners: ['peakxv', 'accel', 'kalaari'],
    knownUniversities: ['iith'],
    knownAccelerators: ['yc', 'sosv', 'plugandplay'],
    knownIncubators: [],
    knownEvents: ['T-Hub Demo Day', 'T-Hub Innovators'],
    engineeringFocus: ['DEEPTECH', 'AI', 'SAAS'],
    internshipLikelihood: 0.78,
    remoteFriendliness: 0.55,
    lastUpdated: UPDATED,
  },
  {
    id: 'nsrcel',
    name: 'NSRCEL',
    type: 'INDIAN_STARTUP_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 1,
    officialWebsite: 'https://nsrcel.org',
    portfolioPage: 'https://nsrcel.org/startups',
    startupDirectory: 'https://nsrcel.org/startups',
    knownCareerPages: ['https://nsrcel.org/careers'],
    knownATS: [],
    knownDomains: [],
    knownPartners: ['peakxv', 'accel'],
    knownUniversities: ['iimb'],
    knownAccelerators: ['yc'],
    knownIncubators: [],
    knownEvents: ['NSRCEL Cohort'],
    engineeringFocus: ['SAAS', 'FINTECH', 'AI'],
    internshipLikelihood: 0.74,
    remoteFriendliness: 0.5,
    lastUpdated: UPDATED,
  },
  {
    id: 'ksum',
    name: 'Kerala Startup Mission',
    type: 'INDIAN_STARTUP_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 2,
    officialWebsite: 'https://startupmission.kerala.gov.in',
    portfolioPage: 'https://startupmission.kerala.gov.in/startups',
    startupDirectory: 'https://startupmission.kerala.gov.in/directory',
    knownCareerPages: ['https://startupmission.kerala.gov.in/careers'],
    knownATS: [],
    knownDomains: [],
    knownPartners: ['thub'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: [],
    knownEvents: ['KSUM Summit'],
    engineeringFocus: ['DEEPTECH', 'SAAS'],
    internshipLikelihood: 0.66,
    remoteFriendliness: 0.5,
    lastUpdated: UPDATED,
  },
  {
    id: 'startuptn',
    name: 'StartupTN',
    type: 'INDIAN_STARTUP_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 2,
    officialWebsite: 'https://startuptn.in',
    portfolioPage: 'https://startuptn.in/startups',
    startupDirectory: 'https://startuptn.in/startups',
    knownCareerPages: ['https://startuptn.in/careers'],
    knownATS: [],
    knownDomains: [],
    knownPartners: ['thub'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: [],
    knownEvents: ['StartupTN Summit'],
    engineeringFocus: ['SAAS', 'DEEPTECH'],
    internshipLikelihood: 0.64,
    remoteFriendliness: 0.5,
    lastUpdated: UPDATED,
  },
  {
    id: 'ciie',
    name: 'CIIE',
    type: 'INDIAN_STARTUP_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 2,
    officialWebsite: 'https://ciie.co',
    portfolioPage: 'https://ciie.co/portfolio',
    knownCareerPages: ['https://ciie.co/careers'],
    knownATS: [],
    knownDomains: [],
    knownPartners: ['peakxv', 'blume'],
    knownUniversities: ['iima'],
    knownAccelerators: ['yc'],
    knownIncubators: [],
    knownEvents: ['CIIE Cohort'],
    engineeringFocus: ['SAAS', 'FINTECH'],
    internshipLikelihood: 0.62,
    remoteFriendliness: 0.5,
    lastUpdated: UPDATED,
  },
  {
    id: 'icreate',
    name: 'iCreate',
    type: 'INDIAN_STARTUP_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 3,
    officialWebsite: 'https://icreate.org.in',
    portfolioPage: 'https://icreate.org.in/startups',
    knownCareerPages: ['https://icreate.org.in/careers'],
    knownATS: [],
    knownDomains: [],
    knownPartners: ['thub'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: [],
    knownEvents: ['iCreate Bioverse'],
    engineeringFocus: ['DEEPTECH', 'AI'],
    internshipLikelihood: 0.6,
    remoteFriendliness: 0.5,
    lastUpdated: UPDATED,
  },
  {
    id: 'aic',
    name: 'AIC',
    type: 'INDIAN_STARTUP_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 3,
    officialWebsite: 'https://www.aicte-india.org',
    portfolioPage: 'https://www.aicte-india.org/internship',
    knownCareerPages: ['https://www.aicte-india.org'],
    knownATS: [],
    knownDomains: [],
    knownPartners: ['thub', 'nsrcel'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: [],
    knownEvents: ['AIC Conclave'],
    engineeringFocus: ['SAAS', 'AI'],
    internshipLikelihood: 0.58,
    remoteFriendliness: 0.5,
    lastUpdated: UPDATED,
  },
  {
    id: 'nasscom',
    name: 'NASSCOM 10K',
    type: 'INDIAN_STARTUP_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 2,
    officialWebsite: 'https://10k.nav.v2.nasscom.in',
    portfolioPage: 'https://10k.nav.v2.nasscom.in/startups',
    startupDirectory: 'https://10k.nav.v2.nasscom.in/startups',
    knownCareerPages: ['https://nasscom.in/careers'],
    knownATS: [],
    knownDomains: [],
    knownPartners: ['thub', 'peakxv'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: [],
    knownEvents: ['NASSCOM Product Conclave'],
    engineeringFocus: ['SAAS', 'AI', 'DEVELOPER_TOOLS'],
    internshipLikelihood: 0.7,
    remoteFriendliness: 0.6,
    lastUpdated: UPDATED,
  },
  {
    id: 'tide',
    name: 'TIDE 2.0',
    type: 'INDIAN_STARTUP_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 3,
    officialWebsite: 'https://tide.msme.gov.in',
    portfolioPage: 'https://tide.msme.gov.in/incubators',
    knownCareerPages: ['https://tide.msme.gov.in'],
    knownATS: [],
    knownDomains: [],
    knownPartners: ['thub'],
    knownUniversities: [],
    knownAccelerators: ['yc'],
    knownIncubators: [],
    knownEvents: ['TIDE Demo Day'],
    engineeringFocus: ['DEEPTECH'],
    internshipLikelihood: 0.54,
    remoteFriendliness: 0.4,
    lastUpdated: UPDATED,
  },
  {
    id: 'meity',
    name: 'MeitY',
    type: 'INDIAN_STARTUP_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 2,
    officialWebsite: 'https://www.meity.gov.in',
    portfolioPage: 'https://www.meity.gov.in/startup',
    knownCareerPages: ['https://www.meity.gov.in'],
    knownATS: [],
    knownDomains: [],
    knownPartners: ['thub', 'nasscom'],
    knownUniversities: [],
    knownAccelerators: [],
    knownIncubators: ['icreate', 'aic'],
    knownEvents: ['MeitY Startup Hub'],
    engineeringFocus: ['DEEPTECH', 'AI'],
    internshipLikelihood: 0.6,
    remoteFriendliness: 0.5,
    lastUpdated: UPDATED,
  },
  {
    id: 'stpi',
    name: 'STPI',
    type: 'INDIAN_STARTUP_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 3,
    officialWebsite: 'https://www.stpi.in',
    portfolioPage: 'https://www.stpi.in/incubation',
    knownCareerPages: ['https://www.stpi.in'],
    knownATS: [],
    knownDomains: [],
    knownPartners: ['thub', 'ksum'],
    knownUniversities: [],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['STPI NextGen'],
    engineeringFocus: ['SAAS', 'DEEPTECH'],
    internshipLikelihood: 0.56,
    remoteFriendliness: 0.5,
    lastUpdated: UPDATED,
  },

  // ─── Research ecosystems ────────────────────────────────────────────────
  {
    id: 'msr',
    name: 'Microsoft Research',
    type: 'RESEARCH_ECOSYSTEM',
    country: 'USA',
    region: 'GLOBAL',
    priority: 1,
    officialWebsite: 'https://www.microsoft.com/en-us/research',
    portfolioPage: 'https://www.microsoft.com/en-us/research/people',
    knownCareerPages: ['https://www.microsoft.com/en-us/research/careers'],
    knownATS: [],
    knownDomains: ['microsoft.com'],
    knownPartners: [],
    knownUniversities: ['iisc', 'iitb', 'iitd'],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['MSR Internship'],
    engineeringFocus: ['AI', 'RESEARCH', 'CLOUD'],
    internshipLikelihood: 0.88,
    remoteFriendliness: 0.5,
    lastUpdated: UPDATED,
  },
  {
    id: 'googleresearch',
    name: 'Google Research',
    type: 'RESEARCH_ECOSYSTEM',
    country: 'USA',
    region: 'GLOBAL',
    priority: 1,
    officialWebsite: 'https://research.google',
    portfolioPage: 'https://research.google/teams',
    knownCareerPages: ['https://research.google/careers', 'https://careers.google.com/students'],
    knownATS: [],
    knownDomains: ['google.com'],
    knownPartners: [],
    knownUniversities: ['iisc', 'iitb', 'iitm'],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['Google Research Internship'],
    engineeringFocus: ['AI', 'RESEARCH'],
    internshipLikelihood: 0.9,
    remoteFriendliness: 0.5,
    lastUpdated: UPDATED,
  },
  {
    id: 'deepmind',
    name: 'DeepMind',
    type: 'RESEARCH_ECOSYSTEM',
    country: 'UK',
    region: 'EUROPE',
    priority: 1,
    officialWebsite: 'https://www.deepmind.com',
    knownCareerPages: ['https://www.deepmind.com/careers', 'https://deepmind.google/about/careers'],
    knownATS: [],
    knownDomains: ['deepmind.com'],
    knownPartners: ['googleresearch'],
    knownUniversities: ['iisc'],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['DeepMind Internship'],
    engineeringFocus: ['AI', 'RESEARCH'],
    internshipLikelihood: 0.86,
    remoteFriendliness: 0.5,
    lastUpdated: UPDATED,
  },
  {
    id: 'openai',
    name: 'OpenAI',
    type: 'RESEARCH_ECOSYSTEM',
    country: 'USA',
    region: 'GLOBAL',
    priority: 1,
    officialWebsite: 'https://openai.com',
    knownCareerPages: [
      'https://openai.com/careers',
      'https://openai.com/index/our-internship-program',
    ],
    knownATS: ['Greenhouse'],
    knownDomains: ['openai.com'],
    knownPartners: ['yc'],
    knownUniversities: ['iisc', 'iitb'],
    knownAccelerators: ['yc'],
    knownIncubators: [],
    knownEvents: ['OpenAI Internship'],
    engineeringFocus: ['AI', 'RESEARCH'],
    internshipLikelihood: 0.9,
    remoteFriendliness: 0.6,
    lastUpdated: UPDATED,
  },
  {
    id: 'iisc',
    name: 'IISc',
    type: 'RESEARCH_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 1,
    officialWebsite: 'https://iisc.ac.in',
    portfolioPage: 'https://iisc.ac.in/research',
    knownCareerPages: ['https://iisc.ac.in/admissions', 'https://careers.iisc.ac.in'],
    knownATS: [],
    knownDomains: ['iisc.ac.in'],
    knownPartners: ['msr', 'googleresearch', 'deepmind'],
    knownUniversities: ['iisc'],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['IISc Summer Fellowship'],
    engineeringFocus: ['RESEARCH', 'DEEPTECH', 'AI'],
    internshipLikelihood: 0.82,
    remoteFriendliness: 0.3,
    lastUpdated: UPDATED,
  },
  {
    id: 'iits',
    name: 'IITs',
    type: 'RESEARCH_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 1,
    officialWebsite: 'https://www.iit.ac.in',
    portfolioPage: 'https://www.iit.ac.in/research',
    knownCareerPages: [
      'https://intern.iitb.ac.in',
      'https://iitm.ac.in/careers',
      'https://iisc.ac.in/admissions',
    ],
    knownATS: [],
    knownDomains: ['iitb.ac.in', 'iitm.ac.in', 'iitd.ac.in', 'iitk.ac.in'],
    knownPartners: ['iisc', 'nsrcel'],
    knownUniversities: ['iitb', 'iitm', 'iitd', 'iitk', 'iith', 'iisc'],
    knownAccelerators: [],
    knownIncubators: ['thub', 'nsrcel'],
    knownEvents: ['IIT Summer Internship'],
    engineeringFocus: ['RESEARCH', 'AI', 'DEEPTECH'],
    internshipLikelihood: 0.8,
    remoteFriendliness: 0.3,
    lastUpdated: UPDATED,
  },
  {
    id: 'iiits',
    name: 'IIITs',
    type: 'RESEARCH_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 2,
    officialWebsite: 'https://www.iiit.ac.in',
    portfolioPage: 'https://www.iiit.ac.in/research',
    knownCareerPages: ['https://www.iiit.ac.in/admissions', 'https://iiith.ac.in/careers'],
    knownATS: [],
    knownDomains: ['iiit.ac.in', 'iiith.ac.in'],
    knownPartners: ['iits', 'thub'],
    knownUniversities: ['iiitb', 'iiith'],
    knownAccelerators: [],
    knownIncubators: ['thub'],
    knownEvents: ['IIIT Research Internship'],
    engineeringFocus: ['RESEARCH', 'AI', 'CYBERSECURITY'],
    internshipLikelihood: 0.74,
    remoteFriendliness: 0.3,
    lastUpdated: UPDATED,
  },
  {
    id: 'drdo',
    name: 'DRDO Labs',
    type: 'RESEARCH_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 2,
    officialWebsite: 'https://www.drdo.gov.in',
    knownCareerPages: ['https://www.drdo.gov.in/careers', 'https://rac.gov.in'],
    knownATS: [],
    knownDomains: ['drdo.gov.in', 'rac.gov.in'],
    knownPartners: ['iisc', 'iits'],
    knownUniversities: ['iisc', 'iits'],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['DRDO Apprenticeship'],
    engineeringFocus: ['RESEARCH', 'DEEPTECH', 'CYBERSECURITY'],
    internshipLikelihood: 0.72,
    remoteFriendliness: 0.2,
    lastUpdated: UPDATED,
  },
  {
    id: 'isro',
    name: 'ISRO Centers',
    type: 'RESEARCH_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 2,
    officialWebsite: 'https://www.isro.gov.in',
    knownCareerPages: ['https://www.isro.gov.in/careers', 'https://www.sac.gov.in'],
    knownATS: [],
    knownDomains: ['isro.gov.in', 'sac.gov.in'],
    knownPartners: ['iisc', 'iits'],
    knownUniversities: ['iisc', 'iits'],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['ISRO Young Scientist Programme'],
    engineeringFocus: ['DEEPTECH', 'RESEARCH'],
    internshipLikelihood: 0.7,
    remoteFriendliness: 0.2,
    lastUpdated: UPDATED,
  },
  {
    id: 'cdac',
    name: 'CDAC',
    type: 'RESEARCH_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 3,
    officialWebsite: 'https://www.cdac.in',
    knownCareerPages: [
      'https://www.cdac.in/index.aspx?id=careers',
      'https://cdac.in/index.aspx?id=internship',
    ],
    knownATS: [],
    knownDomains: ['cdac.in'],
    knownPartners: ['meity', 'iits'],
    knownUniversities: ['iits'],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['CDAC Internship'],
    engineeringFocus: ['DEEPTECH', 'RESEARCH', 'CLOUD'],
    internshipLikelihood: 0.66,
    remoteFriendliness: 0.2,
    lastUpdated: UPDATED,
  },

  // ─── Developer ecosystems ───────────────────────────────────────────────
  {
    id: 'github',
    name: 'GitHub',
    type: 'DEVELOPER_ECOSYSTEM',
    country: 'USA',
    region: 'GLOBAL',
    priority: 1,
    officialWebsite: 'https://github.com',
    knownCareerPages: ['https://github.com/about/careers'],
    knownATS: ['Greenhouse'],
    knownDomains: ['github.com'],
    knownPartners: ['vercel', 'cloudflare'],
    knownUniversities: [],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['GitHub Octernship'],
    engineeringFocus: ['OPEN_SOURCE', 'DEVELOPER_TOOLS'],
    internshipLikelihood: 0.8,
    remoteFriendliness: 0.9,
    lastUpdated: UPDATED,
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    type: 'DEVELOPER_ECOSYSTEM',
    country: 'USA',
    region: 'GLOBAL',
    priority: 1,
    officialWebsite: 'https://www.cloudflare.com',
    knownCareerPages: ['https://www.cloudflare.com/careers'],
    knownATS: ['Greenhouse'],
    knownDomains: ['cloudflare.com'],
    knownPartners: ['github', 'vercel'],
    knownUniversities: [],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['Cloudflare Internship'],
    engineeringFocus: ['CLOUD', 'CYBERSECURITY', 'DEVELOPER_TOOLS'],
    internshipLikelihood: 0.82,
    remoteFriendliness: 0.85,
    lastUpdated: UPDATED,
  },
  {
    id: 'vercel',
    name: 'Vercel',
    type: 'DEVELOPER_ECOSYSTEM',
    country: 'USA',
    region: 'GLOBAL',
    priority: 1,
    officialWebsite: 'https://vercel.com',
    knownCareerPages: ['https://vercel.com/careers'],
    knownATS: ['Ashby'],
    knownDomains: ['vercel.com'],
    knownPartners: ['github', 'cloudflare'],
    knownUniversities: [],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['Vercel Internship'],
    engineeringFocus: ['DEVELOPER_TOOLS', 'CLOUD', 'OPEN_SOURCE'],
    internshipLikelihood: 0.78,
    remoteFriendliness: 0.9,
    lastUpdated: UPDATED,
  },
  {
    id: 'netlify',
    name: 'Netlify',
    type: 'DEVELOPER_ECOSYSTEM',
    country: 'USA',
    region: 'GLOBAL',
    priority: 2,
    officialWebsite: 'https://www.netlify.com',
    knownCareerPages: ['https://www.netlify.com/careers'],
    knownATS: ['Greenhouse'],
    knownDomains: ['netlify.com'],
    knownPartners: ['vercel', 'github'],
    knownUniversities: [],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['Netlify Internship'],
    engineeringFocus: ['DEVELOPER_TOOLS', 'CLOUD'],
    internshipLikelihood: 0.7,
    remoteFriendliness: 0.85,
    lastUpdated: UPDATED,
  },
  {
    id: 'supabase',
    name: 'Supabase',
    type: 'DEVELOPER_ECOSYSTEM',
    country: 'USA',
    region: 'GLOBAL',
    priority: 1,
    officialWebsite: 'https://supabase.com',
    knownCareerPages: ['https://supabase.com/careers'],
    knownATS: ['Ashby'],
    knownDomains: ['supabase.com'],
    knownPartners: ['github', 'vercel'],
    knownUniversities: [],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['Supabase Internship'],
    engineeringFocus: ['DEVELOPER_TOOLS', 'OPEN_SOURCE', 'CLOUD'],
    internshipLikelihood: 0.76,
    remoteFriendliness: 0.9,
    lastUpdated: UPDATED,
  },
  {
    id: 'planetscale',
    name: 'PlanetScale',
    type: 'DEVELOPER_ECOSYSTEM',
    country: 'USA',
    region: 'GLOBAL',
    priority: 2,
    officialWebsite: 'https://planetscale.com',
    knownCareerPages: ['https://planetscale.com/careers'],
    knownATS: ['Ashby'],
    knownDomains: ['planetscale.com'],
    knownPartners: ['github', 'vercel'],
    knownUniversities: [],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['PlanetScale Internship'],
    engineeringFocus: ['DEVELOPER_TOOLS', 'CLOUD'],
    internshipLikelihood: 0.68,
    remoteFriendliness: 0.85,
    lastUpdated: UPDATED,
  },
  {
    id: 'hashicorp',
    name: 'HashiCorp',
    type: 'DEVELOPER_ECOSYSTEM',
    country: 'USA',
    region: 'GLOBAL',
    priority: 2,
    officialWebsite: 'https://www.hashicorp.com',
    knownCareerPages: ['https://www.hashicorp.com/careers'],
    knownATS: ['Greenhouse'],
    knownDomains: ['hashicorp.com'],
    knownPartners: ['github', 'cloudflare'],
    knownUniversities: [],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['HashiCorp Internship'],
    engineeringFocus: ['DEVELOPER_TOOLS', 'CLOUD', 'DEVOPS'],
    internshipLikelihood: 0.72,
    remoteFriendliness: 0.8,
    lastUpdated: UPDATED,
  },
  {
    id: 'docker',
    name: 'Docker',
    type: 'DEVELOPER_ECOSYSTEM',
    country: 'USA',
    region: 'GLOBAL',
    priority: 2,
    officialWebsite: 'https://www.docker.com',
    knownCareerPages: ['https://www.docker.com/careers'],
    knownATS: ['Greenhouse'],
    knownDomains: ['docker.com'],
    knownPartners: ['github', 'vercel'],
    knownUniversities: [],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['Docker Internship'],
    engineeringFocus: ['DEVELOPER_TOOLS', 'CLOUD', 'OPEN_SOURCE'],
    internshipLikelihood: 0.7,
    remoteFriendliness: 0.8,
    lastUpdated: UPDATED,
  },
  {
    id: 'redis',
    name: 'Redis',
    type: 'DEVELOPER_ECOSYSTEM',
    country: 'USA',
    region: 'GLOBAL',
    priority: 2,
    officialWebsite: 'https://redis.io',
    knownCareerPages: ['https://redis.io/careers'],
    knownATS: ['Lever'],
    knownDomains: ['redis.io', 'redis.com'],
    knownPartners: ['github', 'vercel'],
    knownUniversities: [],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['Redis Internship'],
    engineeringFocus: ['DEVELOPER_TOOLS', 'OPEN_SOURCE', 'CLOUD'],
    internshipLikelihood: 0.7,
    remoteFriendliness: 0.8,
    lastUpdated: UPDATED,
  },
  {
    id: 'grafana',
    name: 'Grafana',
    type: 'DEVELOPER_ECOSYSTEM',
    country: 'USA',
    region: 'GLOBAL',
    priority: 2,
    officialWebsite: 'https://grafana.com',
    knownCareerPages: ['https://grafana.com/about/careers'],
    knownATS: [],
    knownDomains: ['grafana.com'],
    knownPartners: ['github', 'cloudflare'],
    knownUniversities: [],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['Grafana Internship'],
    engineeringFocus: ['DEVELOPER_TOOLS', 'CLOUD', 'OPEN_SOURCE'],
    internshipLikelihood: 0.68,
    remoteFriendliness: 0.85,
    lastUpdated: UPDATED,
  },

  // ─── Hackathon ecosystems ───────────────────────────────────────────────
  {
    id: 'devfolio',
    name: 'Devfolio',
    type: 'HACKATHON_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 1,
    officialWebsite: 'https://devfolio.co',
    portfolioPage: 'https://devfolio.co/hackathons',
    knownCareerPages: ['https://devfolio.co/careers'],
    knownATS: [],
    knownDomains: ['devfolio.co'],
    knownPartners: ['unstop', 'mlh'],
    knownUniversities: ['iits', 'iiits'],
    knownAccelerators: [],
    knownIncubators: ['thub'],
    knownEvents: ['Devfolio Hackathons'],
    engineeringFocus: ['AI', 'OPEN_SOURCE', 'CLOUD'],
    internshipLikelihood: 0.5,
    remoteFriendliness: 0.9,
    lastUpdated: UPDATED,
  },
  {
    id: 'devpost',
    name: 'Devpost',
    type: 'HACKATHON_ECOSYSTEM',
    country: 'USA',
    region: 'GLOBAL',
    priority: 1,
    officialWebsite: 'https://devpost.com',
    portfolioPage: 'https://devpost.com/hackathons',
    knownCareerPages: ['https://devpost.com/careers'],
    knownATS: [],
    knownDomains: ['devpost.com'],
    knownPartners: ['mlh', 'unstop'],
    knownUniversities: [],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['Devpost Hackathons'],
    engineeringFocus: ['AI', 'SAAS', 'OPEN_SOURCE'],
    internshipLikelihood: 0.48,
    remoteFriendliness: 0.95,
    lastUpdated: UPDATED,
  },
  {
    id: 'mlh',
    name: 'MLH',
    type: 'HACKATHON_ECOSYSTEM',
    country: 'USA',
    region: 'GLOBAL',
    priority: 1,
    officialWebsite: 'https://mlh.io',
    portfolioPage: 'https://mlh.io/seasons/2024/events',
    knownCareerPages: ['https://mlh.io/careers'],
    knownATS: [],
    knownDomains: ['mlh.io'],
    knownPartners: ['devpost', 'devfolio'],
    knownUniversities: [],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['MLH Season'],
    engineeringFocus: ['AI', 'OPEN_SOURCE', 'WEB'],
    internshipLikelihood: 0.46,
    remoteFriendliness: 0.95,
    lastUpdated: UPDATED,
  },
  {
    id: 'unstop',
    name: 'Unstop',
    type: 'HACKATHON_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 1,
    officialWebsite: 'https://unstop.com',
    portfolioPage: 'https://unstop.com/hackathons',
    knownCareerPages: ['https://unstop.com/careers'],
    knownATS: [],
    knownDomains: ['unstop.com'],
    knownPartners: ['devfolio', 'devpost'],
    knownUniversities: ['iits', 'iiits'],
    knownAccelerators: [],
    knownIncubators: ['thub'],
    knownEvents: ['Unstop Competitions'],
    engineeringFocus: ['AI', 'SAAS', 'OPEN_SOURCE'],
    internshipLikelihood: 0.5,
    remoteFriendliness: 0.9,
    lastUpdated: UPDATED,
  },
  {
    id: 'ethglobal',
    name: 'ETHGlobal',
    type: 'HACKATHON_ECOSYSTEM',
    country: 'USA',
    region: 'GLOBAL',
    priority: 2,
    officialWebsite: 'https://ethglobal.com',
    portfolioPage: 'https://ethglobal.com/events',
    knownCareerPages: ['https://ethglobal.com/careers'],
    knownATS: [],
    knownDomains: ['ethglobal.com'],
    knownPartners: ['devpost', 'mlh'],
    knownUniversities: [],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['ETHGlobal Events'],
    engineeringFocus: ['BLOCKCHAIN', 'WEB3', 'OPEN_SOURCE'],
    internshipLikelihood: 0.44,
    remoteFriendliness: 1.0,
    lastUpdated: UPDATED,
  },
  {
    id: 'hack2skill',
    name: 'Hack2Skill',
    type: 'HACKATHON_ECOSYSTEM',
    country: 'India',
    region: 'INDIA',
    priority: 2,
    officialWebsite: 'https://hack2skill.com',
    portfolioPage: 'https://hack2skill.com/hackathons',
    knownCareerPages: ['https://hack2skill.com/careers'],
    knownATS: [],
    knownDomains: ['hack2skill.com'],
    knownPartners: ['unstop', 'devfolio'],
    knownUniversities: ['iits'],
    knownAccelerators: [],
    knownIncubators: ['thub'],
    knownEvents: ['Hack2Skill Events'],
    engineeringFocus: ['AI', 'CLOUD', 'OPEN_SOURCE'],
    internshipLikelihood: 0.46,
    remoteFriendliness: 0.9,
    lastUpdated: UPDATED,
  },
  {
    id: 'gdg',
    name: 'Google Developer Groups',
    type: 'HACKATHON_ECOSYSTEM',
    country: 'Global',
    region: 'GLOBAL',
    priority: 2,
    officialWebsite: 'https://developers.google.com/community/gdg',
    portfolioPage: 'https://gdg.community.dev',
    knownCareerPages: ['https://developers.google.com/careers'],
    knownATS: [],
    knownDomains: ['developers.google.com', 'gdg.community.dev'],
    knownPartners: ['devpost', 'mlh'],
    knownUniversities: ['iits'],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['GDG DevFest'],
    engineeringFocus: ['AI', 'CLOUD', 'OPEN_SOURCE'],
    internshipLikelihood: 0.42,
    remoteFriendliness: 0.9,
    lastUpdated: UPDATED,
  },
  {
    id: 'mslearn',
    name: 'Microsoft Learn',
    type: 'HACKATHON_ECOSYSTEM',
    country: 'Global',
    region: 'GLOBAL',
    priority: 2,
    officialWebsite: 'https://learn.microsoft.com',
    portfolioPage: 'https://learn.microsoft.com/en-us/events',
    knownCareerPages: ['https://careers.microsoft.com'],
    knownATS: [],
    knownDomains: ['learn.microsoft.com', 'microsoft.com'],
    knownPartners: ['gdg', 'awscommunity'],
    knownUniversities: ['iits'],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['Microsoft Learn Student Ambassadors'],
    engineeringFocus: ['CLOUD', 'AI', 'OPEN_SOURCE'],
    internshipLikelihood: 0.44,
    remoteFriendliness: 0.9,
    lastUpdated: UPDATED,
  },
  {
    id: 'awscommunity',
    name: 'AWS Community',
    type: 'HACKATHON_ECOSYSTEM',
    country: 'Global',
    region: 'GLOBAL',
    priority: 2,
    officialWebsite: 'https://community.aws',
    portfolioPage: 'https://community.aws/learn/aws-community-builders',
    knownCareerPages: ['https://aws.amazon.com/careers'],
    knownATS: [],
    knownDomains: ['community.aws', 'aws.amazon.com'],
    knownPartners: ['mslearn', 'gdg'],
    knownUniversities: ['iits'],
    knownAccelerators: [],
    knownIncubators: [],
    knownEvents: ['AWS Hackdays'],
    engineeringFocus: ['CLOUD', 'AI', 'DEVOPS'],
    internshipLikelihood: 0.42,
    remoteFriendliness: 0.9,
    lastUpdated: UPDATED,
  },
];

/**
 * Deterministic city intelligence registry.
 */
export const CITIES: CityIntel[] = [
  // Priority 1
  {
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    startupScore: 98,
    engineeringScore: 97,
    researchScore: 88,
    governmentScore: 70,
    priority: 1,
    majorIncubators: ['thub', 'nsrcel', 'ciie'],
    majorUniversities: ['iisc', 'iitb', 'iiitb'],
    majorTechParks: ['Electronic City', 'Manyata', 'RMZ EcoWorld'],
  },
  {
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    startupScore: 90,
    engineeringScore: 92,
    researchScore: 84,
    governmentScore: 78,
    priority: 1,
    majorIncubators: ['thub', 'tide'],
    majorUniversities: ['iith', 'iiith'],
    majorTechParks: ['HITEC City', 'Financial District'],
  },
  {
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    startupScore: 82,
    engineeringScore: 88,
    researchScore: 76,
    governmentScore: 64,
    priority: 1,
    majorIncubators: ['nsrcel'],
    majorUniversities: ['iitb'],
    majorTechParks: ['Hinjewadi', 'Magarpatta'],
  },
  {
    city: 'Gurugram',
    state: 'Haryana',
    country: 'India',
    startupScore: 80,
    engineeringScore: 84,
    researchScore: 70,
    governmentScore: 72,
    priority: 1,
    majorIncubators: ['nsrcel'],
    majorUniversities: ['iitd'],
    majorTechParks: ['Cyber City', 'Udyog Vihar'],
  },
  {
    city: 'Noida',
    state: 'Uttar Pradesh',
    country: 'India',
    startupScore: 76,
    engineeringScore: 82,
    researchScore: 66,
    governmentScore: 74,
    priority: 1,
    majorIncubators: ['nsrcel'],
    majorUniversities: ['iitd'],
    majorTechParks: ['Sector 62', 'Film City'],
  },
  {
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    startupScore: 78,
    engineeringScore: 84,
    researchScore: 78,
    governmentScore: 70,
    priority: 1,
    majorIncubators: ['nsrcel', 'ciie'],
    majorUniversities: ['iitm', 'iiitdm'],
    majorTechParks: ['Tidel Park', 'DLF Cybercity'],
  },
  {
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    startupScore: 86,
    engineeringScore: 82,
    researchScore: 72,
    governmentScore: 70,
    priority: 1,
    majorIncubators: ['nsrcel', 'ciie', 'sosv'],
    majorUniversities: ['iitb'],
    majorTechParks: ['BKC', 'Lower Parel'],
  },
  // Priority 2
  {
    city: 'Ahmedabad',
    state: 'Gujarat',
    country: 'India',
    startupScore: 70,
    engineeringScore: 72,
    researchScore: 68,
    governmentScore: 66,
    priority: 2,
    majorIncubators: ['ciie', 'icreate'],
    majorUniversities: ['iima'],
    majorTechParks: ['GIFT City', 'Sanand'],
  },
  {
    city: 'Kochi',
    state: 'Kerala',
    country: 'India',
    startupScore: 66,
    engineeringScore: 70,
    researchScore: 72,
    governmentScore: 74,
    priority: 2,
    majorIncubators: ['ksum'],
    majorUniversities: ['cochin'],
    majorTechParks: ['Infopark', 'SmartCity'],
  },
  {
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    startupScore: 60,
    engineeringScore: 66,
    researchScore: 60,
    governmentScore: 60,
    priority: 2,
    majorIncubators: ['thub'],
    majorUniversities: ['iitindore'],
    majorTechParks: ['Pithampur'],
  },
  {
    city: 'Jaipur',
    state: 'Rajasthan',
    country: 'India',
    startupScore: 62,
    engineeringScore: 68,
    researchScore: 62,
    governmentScore: 62,
    priority: 2,
    majorIncubators: ['thub'],
    majorUniversities: ['mnit'],
    majorTechParks: ['Mahindra SEZ'],
  },
  {
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    country: 'India',
    startupScore: 58,
    engineeringScore: 70,
    researchScore: 64,
    governmentScore: 58,
    priority: 2,
    majorIncubators: ['nsrcel'],
    majorUniversities: ['cit'],
    majorTechParks: ['TIDEL Park Coimbatore'],
  },
  {
    city: 'Bhubaneswar',
    state: 'Odisha',
    country: 'India',
    startupScore: 56,
    engineeringScore: 64,
    researchScore: 66,
    governmentScore: 68,
    priority: 2,
    majorIncubators: ['startuptn'],
    majorUniversities: ['iitbbs'],
    majorTechParks: ['Infocity'],
  },
  {
    city: 'Trivandrum',
    state: 'Kerala',
    country: 'India',
    startupScore: 60,
    engineeringScore: 68,
    researchScore: 74,
    governmentScore: 76,
    priority: 2,
    majorIncubators: ['ksum'],
    majorUniversities: ['ktech'],
    majorTechParks: ['Technopark'],
  },
  {
    city: 'Mysuru',
    state: 'Karnataka',
    country: 'India',
    startupScore: 54,
    engineeringScore: 62,
    researchScore: 60,
    governmentScore: 58,
    priority: 2,
    majorIncubators: ['thub'],
    majorUniversities: ['mysore'],
    majorTechParks: ['Hebbal IT Park'],
  },
];

const ECOSYSTEM_BY_ID = new Map<string, Ecosystem>(ECOSYSTEMS.map((e) => [e.id, e]));
const CITY_BY_NAME = new Map<string, CityIntel>(CITIES.map((c) => [c.city.toLowerCase(), c]));

export function getEcosystem(id: string): Ecosystem | undefined {
  return ECOSYSTEM_BY_ID.get(id.toLowerCase());
}

export function allEcosystems(): Ecosystem[] {
  return ECOSYSTEMS;
}

export function getCity(name: string): CityIntel | undefined {
  return CITY_BY_NAME.get(name.toLowerCase());
}

export function allCities(): CityIntel[] {
  return CITIES;
}

/** Normalizes a URL to a host string (no protocol, no www). */
export function normalizeHost(url: string): string {
  try {
    const host = new URL(url).hostname.toLowerCase().replace(/^www\./, '');
    return host;
  } catch {
    return url
      .toLowerCase()
      .replace(/^www\./, '')
      .replace(/^https?:\/\//, '')
      .replace(/\/.*$/, '');
  }
}

/** Deterministic careers URL inference from a homepage. */
export function deriveCareersUrl(website: string): string {
  const base = website.replace(/\/+$/, '');
  return `${base}/careers`;
}

/** Deterministic ATS board URL inference from a company host + provider. */
export function atsHostFor(provider: string, slug: string): string {
  switch (provider) {
    case 'Greenhouse':
      return `https://boards.greenhouse.io/${slug}`;
    case 'Lever':
      return `https://jobs.lever.co/${slug}`;
    case 'Ashby':
      return `https://jobs.ashbyhq.com/${slug}`;
    case 'Workable':
      return `https://apply.workable.com/${slug}`;
    default:
      return '';
  }
}
