export type OpportunityType =
  | 'INTERNSHIP'
  | 'STARTUP_INTERNSHIP'
  | 'GOVERNMENT_INTERNSHIP'
  | 'RESEARCH_INTERNSHIP'
  | 'HACKATHON'
  | 'COMPETITION'
  | 'OPEN_SOURCE_PROGRAM'
  | 'CAMPUS_AMBASSADOR'
  | 'SCHOLARSHIP'
  | 'SUMMER_SCHOOL'
  | 'BOOTCAMP'
  | 'FELLOWSHIP'
  | 'WOMEN_IN_TECH';

export const OPPORTUNITY_TYPES: OpportunityType[] = [
  'INTERNSHIP',
  'STARTUP_INTERNSHIP',
  'GOVERNMENT_INTERNSHIP',
  'RESEARCH_INTERNSHIP',
  'HACKATHON',
  'COMPETITION',
  'OPEN_SOURCE_PROGRAM',
  'CAMPUS_AMBASSADOR',
  'SCHOLARSHIP',
  'SUMMER_SCHOOL',
  'BOOTCAMP',
  'FELLOWSHIP',
  'WOMEN_IN_TECH',
];

export const BANNED_OPPORTUNITY_TYPES = [
  'JOB',
  'FREELANCE',
  'VOLUNTEER',
  'EVENT',
  'COURSE',
  'PROGRAM',
  'GRANT',
  'OTHER',
] as const;

export type BannedOpportunityType = (typeof BANNED_OPPORTUNITY_TYPES)[number];
