import { MissionConfiguration } from '../types/query.types';
import { SourceCategory } from '@scout/shared';

const INTENT_CATEGORY_MAP: Record<string, SourceCategory> = {
  'Hiring Software Engineering Interns': 'INTERNSHIPS',
  'Remote Backend Internship': 'INTERNSHIPS',
  'Summer SWE Internship': 'INTERNSHIPS',
  'Freshers Engineering Internship': 'INTERNSHIPS',
  'Student Developer Internship': 'INTERNSHIPS',
  'AI Engineering Internship': 'INTERNSHIPS',
  'Cloud Internship': 'INTERNSHIPS',
  'Frontend Internship': 'INTERNSHIPS',
  'Data Engineering Internship': 'INTERNSHIPS',
  'Platform Internship': 'INTERNSHIPS',
  'Systems Internship': 'INTERNSHIPS',
  'DevOps Internship': 'INTERNSHIPS',
  'Cybersecurity Internship': 'INTERNSHIPS',
  'Embedded Internship': 'INTERNSHIPS',
  'Mobile Internship': 'INTERNSHIPS',
  'Full Stack Internship': 'INTERNSHIPS',
  'Backend Developer Intern': 'INTERNSHIPS',
  'Software Engineer Intern 2026': 'INTERNSHIPS',
  'Engineering Internship India': 'INTERNSHIPS',
  'Technical Internship Program': 'INTERNSHIPS',
  'New Grad Software Internship': 'INTERNSHIPS',
  'Off-cycle Engineering Internship': 'INTERNSHIPS',
  'Winter Software Internship': 'INTERNSHIPS',
  'Fall Engineering Internship': 'INTERNSHIPS',
  'Campus Software Engineer Intern': 'INTERNSHIPS',
  'Student Software Development Intern': 'INTERNSHIPS',
  'SRE Internship': 'INTERNSHIPS',
  'Game Development Internship': 'INTERNSHIPS',
  'Robotics Engineering Internship': 'INTERNSHIPS',
  'Computer Science Internship': 'INTERNSHIPS',
  'Startup Software Internship': 'STARTUP_INTERNSHIPS',
  'YC Portfolio Internship': 'STARTUP_INTERNSHIPS',
  'Early Stage Startup Intern': 'STARTUP_INTERNSHIPS',
  'Seed Startup Engineering Intern': 'STARTUP_INTERNSHIPS',
  'Series A Startup Internship': 'STARTUP_INTERNSHIPS',
  'GenAI Startup Internship': 'STARTUP_INTERNSHIPS',
  'Remote Startup Internship': 'STARTUP_INTERNSHIPS',
  'Founding Engineer Intern': 'STARTUP_INTERNSHIPS',
  'AI Startup Internship': 'STARTUP_INTERNSHIPS',
  'Backend Startup Internship': 'STARTUP_INTERNSHIPS',
  'SaaS Startup Internship': 'STARTUP_INTERNSHIPS',
  'Developer Tools Startup Intern': 'STARTUP_INTERNSHIPS',
  'Cloud Startup Internship': 'STARTUP_INTERNSHIPS',
  'Cybersecurity Startup Intern': 'STARTUP_INTERNSHIPS',
  'DeepTech Startup Internship': 'STARTUP_INTERNSHIPS',
  'Pre-seed Startup Intern': 'STARTUP_INTERNSHIPS',
  'Startup Engineering Intern India': 'STARTUP_INTERNSHIPS',
  'Techstars Internship': 'STARTUP_INTERNSHIPS',
  'Antler Internship': 'STARTUP_INTERNSHIPS',
  'Accel Portfolio Internship': 'STARTUP_INTERNSHIPS',
  'Blume Internship': 'STARTUP_INTERNSHIPS',
  'Peak XV Internship': 'STARTUP_INTERNSHIPS',
  'T-Hub Startup Internship': 'STARTUP_INTERNSHIPS',
  'NSRCEL Internship': 'STARTUP_INTERNSHIPS',
  'Bangalore Startup Internship': 'STARTUP_INTERNSHIPS',
  'Hyderabad Startup Internship': 'STARTUP_INTERNSHIPS',
  'Pune Startup Internship': 'STARTUP_INTERNSHIPS',
  'NCR Startup Internship': 'STARTUP_INTERNSHIPS',
  'Startup Career Page Internship': 'STARTUP_INTERNSHIPS',
  'Startup ATS Internship': 'STARTUP_INTERNSHIPS',
  'Fellowship Startup Engineer': 'STARTUP_INTERNSHIPS',
  'ISRO Internship Engineering': 'GOVERNMENT_INTERNSHIP',
  'DRDO Internship Technical': 'GOVERNMENT_INTERNSHIP',
  'CDAC Internship Software': 'GOVERNMENT_INTERNSHIP',
  'NIC Internship Technology': 'GOVERNMENT_INTERNSHIP',
  'Government Engineering Internship': 'GOVERNMENT_INTERNSHIP',
  'AICTE Internship Student': 'GOVERNMENT_INTERNSHIP',
  'MeitY Internship Program': 'GOVERNMENT_INTERNSHIP',
  'Smart India Internship': 'GOVERNMENT_INTERNSHIP',
  'Digital India Internship': 'GOVERNMENT_INTERNSHIP',
  'BISAG-N Internship': 'GOVERNMENT_INTERNSHIP',
  'BEL Internship Engineering': 'GOVERNMENT_INTERNSHIP',
  'BHEL Internship Technical': 'GOVERNMENT_INTERNSHIP',
  'HAL Internship Engineering': 'GOVERNMENT_INTERNSHIP',
  'ECIL Internship Software': 'GOVERNMENT_INTERNSHIP',
  'IISc Research Internship': 'RESEARCH_INTERNSHIP',
  'IIT Internship Engineering': 'RESEARCH_INTERNSHIP',
  'IIIT Internship Technology': 'RESEARCH_INTERNSHIP',
  'NIT Internship Technical': 'RESEARCH_INTERNSHIP',
  'Government Research Internship': 'RESEARCH_INTERNSHIP',
  'Public Sector Tech Internship': 'GOVERNMENT_INTERNSHIP',
  'Government Innovation Lab Internship': 'GOVERNMENT_INTERNSHIP',
  'Ministry Technology Internship': 'GOVERNMENT_INTERNSHIP',
  'Student Internship Government': 'GOVERNMENT_INTERNSHIP',
  'Technical Training Government': 'GOVERNMENT_INTERNSHIP',
  'Engineering Trainee Government': 'GOVERNMENT_INTERNSHIP',
  'AI Research Internship': 'RESEARCH_INTERNSHIP',
  'ML Research Internship': 'RESEARCH_INTERNSHIP',
  'Computer Vision Internship': 'RESEARCH_INTERNSHIP',
  'Robotics Internship': 'RESEARCH_INTERNSHIP',
  'Summer Research Program Engineering': 'RESEARCH_INTERNSHIP',
  'Research Assistant Engineering': 'RESEARCH_INTERNSHIP',
  'NLP Internship': 'RESEARCH_INTERNSHIP',
  'Systems Internship Research': 'RESEARCH_INTERNSHIP',
  'University Research Internship': 'RESEARCH_INTERNSHIP',
  'Lab Internship Engineering': 'RESEARCH_INTERNSHIP',
  'Distributed Systems Research': 'RESEARCH_INTERNSHIP',
  'Operating Systems Research': 'RESEARCH_INTERNSHIP',
  'Database Research Internship': 'RESEARCH_INTERNSHIP',
  'Quantum Computing Internship': 'RESEARCH_INTERNSHIP',
  'HCI Research Internship': 'RESEARCH_INTERNSHIP',
  'Embedded Systems Research': 'RESEARCH_INTERNSHIP',
  'Cybersecurity Research Internship': 'RESEARCH_INTERNSHIP',
  'Microsoft Research Internship': 'RESEARCH_INTERNSHIP',
  'Google Research Internship': 'RESEARCH_INTERNSHIP',
  'DeepMind Internship': 'RESEARCH_INTERNSHIP',
  'FAIR Internship': 'RESEARCH_INTERNSHIP',
  'NVIDIA Research Internship': 'RESEARCH_INTERNSHIP',
  'Adobe Research Internship': 'RESEARCH_INTERNSHIP',
  'IBM Research Internship': 'RESEARCH_INTERNSHIP',
  'IISc Research Intern': 'RESEARCH_INTERNSHIP',
  'IIT Research Internship': 'RESEARCH_INTERNSHIP',
  'IIIT Research Internship': 'RESEARCH_INTERNSHIP',
  'Student Research Fellowship': 'RESEARCH_INTERNSHIP',
  'Technical Research Assistant': 'RESEARCH_INTERNSHIP',
  'Engineering Research Program': 'RESEARCH_INTERNSHIP',
  'AI Hackathon Student': 'HACKATHONS',
  'Engineering Hackathon': 'HACKATHONS',
  'Student Hackathon India': 'HACKATHONS',
  'Cybersecurity CTF Competition': 'HACKATHONS',
  'Cloud Hackathon Student': 'HACKATHONS',
  'ML Competition Student': 'HACKATHONS',
  'Coding Competition Engineering': 'HACKATHONS',
  'Open Source Hackathon': 'HACKATHONS',
  'Company Hackathon Student': 'HACKATHONS',
  'University Hackathon Engineering': 'HACKATHONS',
  'Blockchain Hackathon': 'HACKATHONS',
  'Developer Tools Hackathon': 'HACKATHONS',
  'Hackathon Prize Pool': 'HACKATHONS',
  'Remote Hackathon Student': 'HACKATHONS',
  'Hackathon Registration 2026': 'HACKATHONS',
  'National Hackathon Engineering': 'HACKATHONS',
  'International Hackathon Student': 'HACKATHONS',
  'AI Competition Engineering': 'HACKATHONS',
  'Hackathon Hiring Potential': 'HACKATHONS',
  'Student Developer Hackathon': 'HACKATHONS',
  'Tech Hackathon Engineering': 'HACKATHONS',
  'Innovation Challenge Student': 'HACKATHONS',
  'Build Challenge Engineering': 'HACKATHONS',
  'Hackathon Resume Value': 'HACKATHONS',
  'Cybersecurity Competition Student': 'HACKATHONS',
};

export class IntentGenerator {
  static generate(
    config: MissionConfiguration,
  ): { intent: string; category: SourceCategory; reason: string }[] {
    return config.searchIntents.map((intent, index) => {
      const category = INTENT_CATEGORY_MAP[intent] || 'INTERNSHIPS';
      return {
        intent,
        category,
        reason: `Mission-aligned search intent [${index + 1}/${config.searchIntents.length}]`,
      };
    });
  }

  static getCategoryForIntent(intent: string): SourceCategory {
    return INTENT_CATEGORY_MAP[intent] || 'INTERNSHIPS';
  }
}
