import { DiscoveryMission, MissionConfiguration } from '../types/query.types';

export const ENGINEERING_INTERNSHIPS_CONFIG: MissionConfiguration = {
  mission: 'ENGINEERING_INTERNSHIPS',
  searchIntents: [
    'Hiring Software Engineering Interns',
    'Remote Backend Internship',
    'Summer SWE Internship',
    'Freshers Engineering Internship',
    'Student Developer Internship',
    'AI Engineering Internship',
    'Cloud Internship',
    'Frontend Internship',
    'Data Engineering Internship',
    'Platform Internship',
    'Systems Internship',
    'DevOps Internship',
    'Cybersecurity Internship',
    'Embedded Internship',
    'Mobile Internship',
    'Full Stack Internship',
    'Backend Developer Intern',
    'Software Engineer Intern 2026',
    'Engineering Internship India',
    'Technical Internship Program',
    'New Grad Software Internship',
    'Off-cycle Engineering Internship',
    'Winter Software Internship',
    'Fall Engineering Internship',
    'Campus Software Engineer Intern',
    'Student Software Development Intern',
    'SRE Internship',
    'Game Development Internship',
    'Robotics Engineering Internship',
    'Computer Science Internship',
  ],
  prioritySources: [
    'Official Company Careers',
    'ATS Systems',
    'University Portals',
    'Engineering Blogs',
  ],
  priorityEcosystems: [],
  priorityCities: [
    'Bengaluru',
    'Hyderabad',
    'Pune',
    'Gurugram',
    'Noida',
    'Chennai',
    'Mumbai',
    'Ahmedabad',
    'Kochi',
  ],
  preferredATS: [
    'Greenhouse',
    'Lever',
    'Ashby',
    'SmartRecruiters',
    'Workable',
    'BambooHR',
    'Comeet',
    'Rippling',
  ],
  searchBudget: 40,
  maxSearchDepth: 3,
  companyDiscoveryEnabled: true,
  multiHopEnabled: true,
};

export const STARTUP_INTERNSHIPS_CONFIG: MissionConfiguration = {
  mission: 'STARTUP_INTERNSHIPS',
  searchIntents: [
    'Startup Software Internship',
    'YC Portfolio Internship',
    'Early Stage Startup Intern',
    'Seed Startup Engineering Intern',
    'Series A Startup Internship',
    'GenAI Startup Internship',
    'Remote Startup Internship',
    'Founding Engineer Intern',
    'AI Startup Internship',
    'Backend Startup Internship',
    'SaaS Startup Internship',
    'Developer Tools Startup Intern',
    'Cloud Startup Internship',
    'Cybersecurity Startup Intern',
    'DeepTech Startup Internship',
    'Pre-seed Startup Intern',
    'Startup Engineering Intern India',
    'Techstars Internship',
    'Antler Internship',
    'Accel Portfolio Internship',
    'Blume Internship',
    'Peak XV Internship',
    'T-Hub Startup Internship',
    'NSRCEL Internship',
    'Bangalore Startup Internship',
    'Hyderabad Startup Internship',
    'Pune Startup Internship',
    'NCR Startup Internship',
    'Startup Career Page Internship',
    'Startup ATS Internship',
    'Fellowship Startup Engineer',
  ],
  prioritySources: [
    'Incubator Portfolio Companies',
    'Official Company Careers',
    'ATS Systems',
    'Startup Job Boards',
  ],
  priorityEcosystems: [
    'Y Combinator',
    'Techstars',
    'Antler',
    'Entrepreneur First',
    '500 Global',
    'T-Hub',
    'Startup India',
    'NSRCEL',
    'CIIE',
    'Kerala Startup Mission',
    'StartupTN',
    'iCreate',
    'NASSCOM',
    '100X.VC',
    'Peak XV',
    'Accel',
    'Blume',
    'Surge',
  ],
  priorityCities: [
    'Bengaluru',
    'Hyderabad',
    'Pune',
    'Gurugram',
    'Noida',
    'Chennai',
    'Mumbai',
    'Ahmedabad',
    'Kochi',
    'Indore',
  ],
  preferredATS: ['Greenhouse', 'Lever', 'Ashby', 'Workable', 'SmartRecruiters', 'Comeet'],
  searchBudget: 25,
  maxSearchDepth: 3,
  companyDiscoveryEnabled: true,
  multiHopEnabled: true,
};

export const GOVERNMENT_TECH_INTERNSHIPS_CONFIG: MissionConfiguration = {
  mission: 'GOVERNMENT_TECH_INTERNSHIPS',
  searchIntents: [
    'ISRO Internship Engineering',
    'DRDO Internship Technical',
    'CDAC Internship Software',
    'NIC Internship Technology',
    'Government Engineering Internship',
    'AICTE Internship Student',
    'MeitY Internship Program',
    'Smart India Internship',
    'Digital India Internship',
    'BISAG-N Internship',
    'BEL Internship Engineering',
    'BHEL Internship Technical',
    'HAL Internship Engineering',
    'ECIL Internship Software',
    'IISc Research Internship',
    'IIT Internship Engineering',
    'IIIT Internship Technology',
    'NIT Internship Technical',
    'Government Research Internship',
    'Public Sector Tech Internship',
    'Government Innovation Lab Internship',
    'Ministry Technology Internship',
    'Student Internship Government',
    'Technical Training Government',
    'Engineering Trainee Government',
  ],
  prioritySources: [
    'Official Portals',
    'Government Announcements',
    'Institute Portals',
    'Research Labs',
  ],
  priorityEcosystems: [],
  priorityCities: ['Bengaluru', 'Hyderabad', 'Pune', 'Chennai', 'Mumbai', 'Ahmedabad', 'Kochi'],
  preferredATS: [],
  searchBudget: 15,
  maxSearchDepth: 2,
  companyDiscoveryEnabled: false,
  multiHopEnabled: false,
};

export const RESEARCH_INTERNSHIPS_CONFIG: MissionConfiguration = {
  mission: 'RESEARCH_INTERNSHIPS',
  searchIntents: [
    'AI Research Internship',
    'ML Research Internship',
    'Computer Vision Internship',
    'Robotics Internship',
    'Summer Research Program Engineering',
    'Research Assistant Engineering',
    'NLP Internship',
    'Systems Internship Research',
    'University Research Internship',
    'Lab Internship Engineering',
    'Distributed Systems Research',
    'Operating Systems Research',
    'Database Research Internship',
    'Quantum Computing Internship',
    'HCI Research Internship',
    'Embedded Systems Research',
    'Cybersecurity Research Internship',
    'Microsoft Research Internship',
    'Google Research Internship',
    'DeepMind Internship',
    'FAIR Internship',
    'NVIDIA Research Internship',
    'Adobe Research Internship',
    'IBM Research Internship',
    'IISc Research Intern',
    'IIT Research Internship',
    'IIIT Research Internship',
    'Student Research Fellowship',
    'Technical Research Assistant',
    'Engineering Research Program',
  ],
  prioritySources: ['Lab Websites', 'Faculty Pages', 'Research Groups', 'University Portals'],
  priorityEcosystems: [
    'IISc',
    'IITs',
    'IIITs',
    'NITs',
    'Microsoft Research',
    'Google Research',
    'DeepMind',
    'FAIR',
    'NVIDIA Research',
    'Adobe Research',
    'IBM Research',
  ],
  priorityCities: ['Bengaluru', 'Hyderabad', 'Pune', 'Chennai', 'Mumbai'],
  preferredATS: [],
  searchBudget: 10,
  maxSearchDepth: 2,
  companyDiscoveryEnabled: false,
  multiHopEnabled: false,
};

export const HACKATHONS_CONFIG: MissionConfiguration = {
  mission: 'HACKATHONS',
  searchIntents: [
    'AI Hackathon Student',
    'Engineering Hackathon',
    'Student Hackathon India',
    'Cybersecurity CTF Competition',
    'Cloud Hackathon Student',
    'ML Competition Student',
    'Coding Competition Engineering',
    'Open Source Hackathon',
    'Company Hackathon Student',
    'University Hackathon Engineering',
    'Blockchain Hackathon',
    'Developer Tools Hackathon',
    'Hackathon Prize Pool',
    'Remote Hackathon Student',
    'Hackathon Registration 2026',
    'National Hackathon Engineering',
    'International Hackathon Student',
    'AI Competition Engineering',
    'Hackathon Hiring Potential',
    'Student Developer Hackathon',
    'Tech Hackathon Engineering',
    'Innovation Challenge Student',
    'Build Challenge Engineering',
    'Hackathon Resume Value',
    'Cybersecurity Competition Student',
  ],
  prioritySources: [
    'Hackathon Platforms',
    'Official Announcements',
    'University Portals',
    'Company Sponsors',
  ],
  priorityEcosystems: [
    'Devpost',
    'Unstop',
    'MLH',
    'Devfolio',
    'Hack2Skill',
    'AngelHack',
    'ETHGlobal',
  ],
  priorityCities: ['Bengaluru', 'Hyderabad', 'Pune', 'Chennai', 'Mumbai', 'Gurugram', 'Noida'],
  preferredATS: [],
  searchBudget: 10,
  maxSearchDepth: 2,
  companyDiscoveryEnabled: false,
  multiHopEnabled: false,
};

export const MISSION_CONFIGS: Record<DiscoveryMission, MissionConfiguration> = {
  ENGINEERING_INTERNSHIPS: ENGINEERING_INTERNSHIPS_CONFIG,
  STARTUP_INTERNSHIPS: STARTUP_INTERNSHIPS_CONFIG,
  GOVERNMENT_TECH_INTERNSHIPS: GOVERNMENT_TECH_INTERNSHIPS_CONFIG,
  RESEARCH_INTERNSHIPS: RESEARCH_INTERNSHIPS_CONFIG,
  HACKATHONS: HACKATHONS_CONFIG,
};
